export interface ChapterMetadata {
  slug: string;
  chapterNumber: number;
  volumeId: number;
  status: 'Researching' | 'Drafting' | 'Reviewing' | 'Locked' | 'Deprecated';
  readingTime: string;
  version: string;
  lastUpdated: string;
  purposeKey: string; // Translation dictionary key path (e.g. "chapters.why-we-are-overwhelmed.purpose")
  keyQuestionKey: string; // Translation dictionary key path
  dependencies: string[]; // slugs
  relatedChapters: string[]; // slugs
  researchConfidence: 'High' | 'Medium' | 'Experimental';
}

export interface AppendixMetadata {
  slug: string;
  appendixNumber: number;
  volumeId: number;
  status: 'Researching' | 'Drafting' | 'Reviewing' | 'Locked' | 'Deprecated';
  readingTime: string;
  version: string;
  lastUpdated: string;
  purposeKey: string;
  keyQuestionKey: string;
  dependencies: string[];
  relatedChapters: string[];
  researchConfidence: 'High' | 'Medium' | 'Experimental';
}

export interface Volume {
  id: number;
  romanId: string;
  titleKey: string; // Translation key (e.g. "volumes.v1.title")
  purposeKey: string; // Translation key (e.g. "volumes.v1.purpose")
  chapters: ChapterMetadata[];
  appendices?: AppendixMetadata[];
}

export const volumes: Volume[] = [
  {
    id: 1,
    romanId: 'I',
    titleKey: 'volumes.v1.title',
    purposeKey: 'volumes.v1.purpose',
    chapters: [
      {
        slug: 'why-we-are-overwhelmed',
        chapterNumber: 1,
        volumeId: 1,
        status: 'Drafting',
        readingTime: '8-10 min',
        version: '0.1',
        lastUpdated: '2026-06-28',
        purposeKey: 'chapters.why-we-are-overwhelmed.purpose',
        keyQuestionKey: 'chapters.why-we-are-overwhelmed.key_question',
        dependencies: [],
        relatedChapters: ['mental-clutter', 'the-attention-crisis'],
        researchConfidence: 'Medium',
      },
      {
        slug: 'mental-clutter',
        chapterNumber: 2,
        volumeId: 1,
        status: 'Drafting',
        readingTime: '6 min',
        version: '0.1',
        lastUpdated: '2026-06-28',
        purposeKey: 'chapters.mental-clutter.purpose',
        keyQuestionKey: 'chapters.mental-clutter.key_question',
        dependencies: ['why-we-are-overwhelmed'],
        relatedChapters: ['why-we-are-overwhelmed', 'open-loops'],
        researchConfidence: 'High',
      },
      {
        slug: 'the-attention-crisis',
        chapterNumber: 3,
        volumeId: 1,
        status: 'Drafting',
        readingTime: '8-10 min',
        version: '0.1',
        lastUpdated: '2026-06-28',
        purposeKey: 'chapters.the-attention-crisis.purpose',
        keyQuestionKey: 'chapters.the-attention-crisis.key_question',
        dependencies: ['why-we-are-overwhelmed', 'mental-clutter'],
        relatedChapters: ['mental-clutter', 'open-loops', 'cost-of-constant-context-switching'],
        researchConfidence: 'Medium',
      },
      {
        slug: 'open-loops',
        chapterNumber: 4,
        volumeId: 1,
        status: 'Drafting',
        readingTime: '5 min',
        version: '0.1',
        lastUpdated: '2026-06-28',
        purposeKey: 'chapters.open-loops.purpose',
        keyQuestionKey: 'chapters.open-loops.key_question',
        dependencies: ['mental-clutter'],
        relatedChapters: ['mental-clutter', 'escape-loops-and-addictions'],
        researchConfidence: 'Medium',
      },
      {
        slug: 'escape-loops-and-addictions',
        chapterNumber: 5,
        volumeId: 1,
        status: 'Drafting',
        readingTime: '6 min',
        version: '0.1',
        lastUpdated: '2026-06-28',
        purposeKey: 'chapters.escape-loops-and-addictions.purpose',
        keyQuestionKey: 'chapters.escape-loops-and-addictions.key_question',
        dependencies: ['the-attention-crisis', 'open-loops'],
        relatedChapters: ['open-loops', 'why-existing-productivity-systems-fail'],
        researchConfidence: 'Medium',
      },
      {
        slug: 'cost-of-constant-context-switching',
        chapterNumber: 6,
        volumeId: 1,
        status: 'Drafting',
        readingTime: '5 min',
        version: '0.1',
        lastUpdated: '2026-06-28',
        purposeKey: 'chapters.cost-of-constant-context-switching.purpose',
        keyQuestionKey: 'chapters.cost-of-constant-context-switching.key_question',
        dependencies: ['the-attention-crisis', 'open-loops'],
        relatedChapters: ['the-attention-crisis', 'why-existing-productivity-systems-fail'],
        researchConfidence: 'Medium',
      },
      {
        slug: 'why-existing-productivity-systems-fail',
        chapterNumber: 7,
        volumeId: 1,
        status: 'Drafting',
        readingTime: '8 min',
        version: '0.1',
        lastUpdated: '2026-06-28',
        purposeKey: 'chapters.why-existing-productivity-systems-fail.purpose',
        keyQuestionKey: 'chapters.why-existing-productivity-systems-fail.key_question',
        dependencies: ['mental-clutter', 'the-attention-crisis', 'open-loops', 'escape-loops-and-addictions', 'cost-of-constant-context-switching'],
        relatedChapters: ['escape-loops-and-addictions', 'cost-of-constant-context-switching'],
        researchConfidence: 'High',
      },
    ],
    appendices: [
      {
        slug: 'volume-1-appendix-1-lonely-optimization',
        appendixNumber: 1,
        volumeId: 1,
        status: 'Drafting',
        readingTime: '10 min',
        version: '0.1',
        lastUpdated: '2026-06-28',
        purposeKey: 'appendices.volume-1-appendix-1-lonely-optimization.purpose',
        keyQuestionKey: 'appendices.volume-1-appendix-1-lonely-optimization.key_question',
        dependencies: [
          'mental-clutter',
          'the-attention-crisis',
          'open-loops',
          'escape-loops-and-addictions',
          'cost-of-constant-context-switching',
          'why-existing-productivity-systems-fail',
          'memory'
        ],
        relatedChapters: [],
        researchConfidence: 'Medium',
      },
    ],
  },
  {
    id: 2,
    romanId: 'II',
    titleKey: 'volumes.v2.title',
    purposeKey: 'volumes.v2.purpose',
    chapters: [
      {
        slug: 'memory',
        chapterNumber: 8,
        volumeId: 2,
        status: 'Drafting',
        readingTime: '7 min',
        version: '0.1',
        lastUpdated: '2026-06-28',
        purposeKey: 'chapters.memory.purpose',
        keyQuestionKey: 'chapters.memory.key_question',
        dependencies: [],
        relatedChapters: ['identity', 'reflection'],
        researchConfidence: 'Medium',
      },
      {
        slug: 'identity',
        chapterNumber: 9,
        volumeId: 2,
        status: 'Drafting',
        readingTime: '6 min',
        version: '0.1',
        lastUpdated: '2026-06-28',
        purposeKey: 'chapters.identity.purpose',
        keyQuestionKey: 'chapters.identity.key_question',
        dependencies: ['memory'],
        relatedChapters: ['memory', 'emotions'],
        researchConfidence: 'Medium',
      },
      {
        slug: 'emotions',
        chapterNumber: 10,
        volumeId: 2,
        status: 'Drafting',
        readingTime: '6 min',
        version: '0.1',
        lastUpdated: '2026-06-28',
        purposeKey: 'chapters.emotions.purpose',
        keyQuestionKey: 'chapters.emotions.key_question',
        dependencies: [],
        relatedChapters: ['identity', 'motivation'],
        researchConfidence: 'Medium',
      },
      {
        slug: 'motivation',
        chapterNumber: 11,
        volumeId: 2,
        status: 'Drafting',
        readingTime: '5 min',
        version: '0.1',
        lastUpdated: '2026-06-28',
        purposeKey: 'chapters.motivation.purpose',
        keyQuestionKey: 'chapters.motivation.key_question',
        dependencies: ['emotions'],
        relatedChapters: ['emotions', 'habits'],
        researchConfidence: 'Medium',
      },
      {
        slug: 'habits',
        chapterNumber: 12,
        volumeId: 2,
        status: 'Drafting',
        readingTime: '6 min',
        version: '0.1',
        lastUpdated: '2026-06-28',
        purposeKey: 'chapters.habits.purpose',
        keyQuestionKey: 'chapters.habits.key_question',
        dependencies: ['motivation'],
        relatedChapters: ['motivation', 'decision-making'],
        researchConfidence: 'High',
      },
      {
        slug: 'decision-making',
        chapterNumber: 13,
        volumeId: 2,
        status: 'Drafting',
        readingTime: '7 min',
        version: '0.1',
        lastUpdated: '2026-06-28',
        purposeKey: 'chapters.decision-making.purpose',
        keyQuestionKey: 'chapters.decision-making.key_question',
        dependencies: ['habits'],
        relatedChapters: ['habits', 'relationships'],
        researchConfidence: 'Medium',
      },
      {
        slug: 'relationships',
        chapterNumber: 14,
        volumeId: 2,
        status: 'Drafting',
        readingTime: '8 min',
        version: '0.1',
        lastUpdated: '2026-06-28',
        purposeKey: 'chapters.relationships.purpose',
        keyQuestionKey: 'chapters.relationships.key_question',
        dependencies: [],
        relatedChapters: ['identity', 'decision-making'],
        researchConfidence: 'Medium',
      },
      {
        slug: 'reflection',
        chapterNumber: 15,
        volumeId: 2,
        status: 'Drafting',
        readingTime: '6 min',
        version: '0.1',
        lastUpdated: '2026-06-28',
        purposeKey: 'chapters.reflection.purpose',
        keyQuestionKey: 'chapters.reflection.key_question',
        dependencies: ['memory'],
        relatedChapters: ['memory', 'meaning'],
        researchConfidence: 'High',
      },
      {
        slug: 'meaning',
        chapterNumber: 16,
        volumeId: 2,
        status: 'Drafting',
        readingTime: '8 min',
        version: '0.1',
        lastUpdated: '2026-06-28',
        purposeKey: 'chapters.meaning.purpose',
        keyQuestionKey: 'chapters.meaning.key_question',
        dependencies: ['reflection'],
        relatedChapters: ['reflection', 'identity'],
        researchConfidence: 'Experimental',
      },
    ],
    appendices: [
      {
        slug: 'volume-2-appendix-1-body-energy-and-capacity',
        appendixNumber: 1,
        volumeId: 2,
        status: 'Drafting',
        readingTime: '9 min',
        version: '0.1',
        lastUpdated: '2026-06-28',
        purposeKey: 'appendices.volume-2-appendix-1-body-energy-and-capacity.purpose',
        keyQuestionKey: 'appendices.volume-2-appendix-1-body-energy-and-capacity.key_question',
        dependencies: ['emotions', 'motivation', 'habits', 'decision-making', 'reflection'],
        relatedChapters: ['memory', 'emotions', 'motivation'],
        researchConfidence: 'Medium',
      },
    ],
  },
  {
    id: 3,
    romanId: 'III',
    titleKey: 'volumes.v3.title',
    purposeKey: 'volumes.v3.purpose',
    chapters: [
      {
        slug: 'why-saule-exists',
        chapterNumber: 17,
        volumeId: 3,
        status: 'Researching',
        readingTime: '6 min',
        version: '0.1',
        lastUpdated: '2026-06-28',
        purposeKey: 'chapters.why-saule-exists.purpose',
        keyQuestionKey: 'chapters.why-saule-exists.key_question',
        dependencies: ['why-we-are-overwhelmed'],
        relatedChapters: ['human-first-ai', 'adaptive-intelligence'],
        researchConfidence: 'High',
      },
      {
        slug: 'human-first-ai',
        chapterNumber: 18,
        volumeId: 3,
        status: 'Researching',
        readingTime: '5 min',
        version: '0.1',
        lastUpdated: '2026-06-28',
        purposeKey: 'chapters.human-first-ai.purpose',
        keyQuestionKey: 'chapters.human-first-ai.key_question',
        dependencies: ['why-saule-exists'],
        relatedChapters: ['why-saule-exists', 'ethics'],
        researchConfidence: 'High',
      },
      {
        slug: 'adaptive-intelligence',
        chapterNumber: 19,
        volumeId: 3,
        status: 'Researching',
        readingTime: '7 min',
        version: '0.1',
        lastUpdated: '2026-06-28',
        purposeKey: 'chapters.adaptive-intelligence.purpose',
        keyQuestionKey: 'chapters.adaptive-intelligence.key_question',
        dependencies: ['why-saule-exists'],
        relatedChapters: ['learning', 'human-agency'],
        researchConfidence: 'High',
      },
      {
        slug: 'trust',
        chapterNumber: 20,
        volumeId: 3,
        status: 'Researching',
        readingTime: '6 min',
        version: '0.1',
        lastUpdated: '2026-06-28',
        purposeKey: 'chapters.trust.purpose',
        keyQuestionKey: 'chapters.trust.key_question',
        dependencies: ['human-first-ai'],
        relatedChapters: ['ethics', 'forgetting'],
        researchConfidence: 'High',
      },
      {
        slug: 'learning',
        chapterNumber: 21,
        volumeId: 3,
        status: 'Researching',
        readingTime: '5 min',
        version: '0.1',
        lastUpdated: '2026-06-28',
        purposeKey: 'chapters.learning.purpose',
        keyQuestionKey: 'chapters.learning.key_question',
        dependencies: ['adaptive-intelligence'],
        relatedChapters: ['adaptive-intelligence', 'forgetting'],
        researchConfidence: 'Medium',
      },
      {
        slug: 'forgetting',
        chapterNumber: 22,
        volumeId: 3,
        status: 'Researching',
        readingTime: '6 min',
        version: '0.1',
        lastUpdated: '2026-06-28',
        purposeKey: 'chapters.forgetting.purpose',
        keyQuestionKey: 'chapters.forgetting.key_question',
        dependencies: ['learning'],
        relatedChapters: ['learning', 'trust'],
        researchConfidence: 'Medium',
      },
      {
        slug: 'ethics',
        chapterNumber: 23,
        volumeId: 3,
        status: 'Researching',
        readingTime: '7 min',
        version: '0.1',
        lastUpdated: '2026-06-28',
        purposeKey: 'chapters.ethics.purpose',
        keyQuestionKey: 'chapters.ethics.key_question',
        dependencies: ['trust'],
        relatedChapters: ['trust', 'human-agency'],
        researchConfidence: 'High',
      },
      {
        slug: 'human-agency',
        chapterNumber: 24,
        volumeId: 3,
        status: 'Researching',
        readingTime: '6 min',
        version: '0.1',
        lastUpdated: '2026-06-28',
        purposeKey: 'chapters.human-agency.purpose',
        keyQuestionKey: 'chapters.human-agency.key_question',
        dependencies: ['ethics'],
        relatedChapters: ['ethics', 'adaptive-intelligence'],
        researchConfidence: 'High',
      },
    ],
  },
  {
    id: 4,
    romanId: 'IV',
    titleKey: 'volumes.v4.title',
    purposeKey: 'volumes.v4.purpose',
    chapters: [
      {
        slug: 'adaptive-memory',
        chapterNumber: 25,
        volumeId: 4,
        status: 'Researching',
        readingTime: '8 min',
        version: '0.1',
        lastUpdated: '2026-06-28',
        purposeKey: 'chapters.adaptive-memory.purpose',
        keyQuestionKey: 'chapters.adaptive-memory.key_question',
        dependencies: ['memory', 'forgetting'],
        relatedChapters: ['context-engine', 'native-intelligence'],
        researchConfidence: 'Medium',
      },
      {
        slug: 'context-engine',
        chapterNumber: 26,
        volumeId: 4,
        status: 'Researching',
        readingTime: '7 min',
        version: '0.1',
        lastUpdated: '2026-06-28',
        purposeKey: 'chapters.context-engine.purpose',
        keyQuestionKey: 'chapters.context-engine.key_question',
        dependencies: ['adaptive-memory'],
        relatedChapters: ['adaptive-memory', 'reflection-engine'],
        researchConfidence: 'Medium',
      },
      {
        slug: 'reflection-engine',
        chapterNumber: 27,
        volumeId: 4,
        status: 'Researching',
        readingTime: '6 min',
        version: '0.1',
        lastUpdated: '2026-06-28',
        purposeKey: 'chapters.reflection-engine.purpose',
        keyQuestionKey: 'chapters.reflection-engine.key_question',
        dependencies: ['reflection', 'context-engine'],
        relatedChapters: ['context-engine', 'coaching-engine'],
        researchConfidence: 'High',
      },
      {
        slug: 'coaching-engine',
        chapterNumber: 28,
        volumeId: 4,
        status: 'Researching',
        readingTime: '8 min',
        version: '0.1',
        lastUpdated: '2026-06-28',
        purposeKey: 'chapters.coaching-engine.purpose',
        keyQuestionKey: 'chapters.coaching-engine.key_question',
        dependencies: ['reflection-engine'],
        relatedChapters: ['reflection-engine', 'career-intelligence'],
        researchConfidence: 'Medium',
      },
      {
        slug: 'career-intelligence',
        chapterNumber: 29,
        volumeId: 4,
        status: 'Researching',
        readingTime: '7 min',
        version: '0.1',
        lastUpdated: '2026-06-28',
        purposeKey: 'chapters.career-intelligence.purpose',
        keyQuestionKey: 'chapters.career-intelligence.key_question',
        dependencies: ['coaching-engine'],
        relatedChapters: ['coaching-engine', 'relationship-intelligence'],
        researchConfidence: 'Medium',
      },
      {
        slug: 'relationship-intelligence',
        chapterNumber: 30,
        volumeId: 4,
        status: 'Researching',
        readingTime: '7 min',
        version: '0.1',
        lastUpdated: '2026-06-28',
        purposeKey: 'chapters.relationship-intelligence.purpose',
        keyQuestionKey: 'chapters.relationship-intelligence.key_question',
        dependencies: ['coaching-engine'],
        relatedChapters: ['career-intelligence', 'planning-intelligence'],
        researchConfidence: 'Medium',
      },
      {
        slug: 'planning-intelligence',
        chapterNumber: 31,
        volumeId: 4,
        status: 'Researching',
        readingTime: '6 min',
        version: '0.1',
        lastUpdated: '2026-06-28',
        purposeKey: 'chapters.planning-intelligence.purpose',
        keyQuestionKey: 'chapters.planning-intelligence.key_question',
        dependencies: ['why-planning-fails'],
        relatedChapters: ['why-planning-fails', 'phone-context'],
        researchConfidence: 'High',
      },
      {
        slug: 'phone-context',
        chapterNumber: 32,
        volumeId: 4,
        status: 'Researching',
        readingTime: '7 min',
        version: '0.1',
        lastUpdated: '2026-06-28',
        purposeKey: 'chapters.phone-context.purpose',
        keyQuestionKey: 'chapters.phone-context.key_question',
        dependencies: ['phone-context'],
        relatedChapters: ['planning-intelligence', 'voice'],
        researchConfidence: 'Medium',
      },
      {
        slug: 'voice',
        chapterNumber: 33,
        volumeId: 4,
        status: 'Researching',
        readingTime: '5 min',
        version: '0.1',
        lastUpdated: '2026-06-28',
        purposeKey: 'chapters.voice.purpose',
        keyQuestionKey: 'chapters.voice.key_question',
        dependencies: [],
        relatedChapters: ['phone-context', 'native-intelligence'],
        researchConfidence: 'Medium',
      },
      {
        slug: 'native-intelligence',
        chapterNumber: 34,
        volumeId: 4,
        status: 'Researching',
        readingTime: '8 min',
        version: '0.1',
        lastUpdated: '2026-06-28',
        purposeKey: 'chapters.native-intelligence.purpose',
        keyQuestionKey: 'chapters.native-intelligence.key_question',
        dependencies: ['adaptive-memory', 'voice'],
        relatedChapters: ['adaptive-memory', 'voice'],
        researchConfidence: 'Experimental',
      },
    ],
  },
  {
    id: 5,
    romanId: 'V',
    titleKey: 'volumes.v5.title',
    purposeKey: 'volumes.v5.purpose',
    chapters: [
      {
        slug: 'ai-architecture',
        chapterNumber: 35,
        volumeId: 5,
        status: 'Researching',
        readingTime: '7 min',
        version: '0.1',
        lastUpdated: '2026-06-28',
        purposeKey: 'chapters.ai-architecture.purpose',
        keyQuestionKey: 'chapters.ai-architecture.key_question',
        dependencies: ['context-engine'],
        relatedChapters: ['engineering-principles', 'security'],
        researchConfidence: 'High',
      },
      {
        slug: 'engineering-principles',
        chapterNumber: 36,
        volumeId: 5,
        status: 'Researching',
        readingTime: '6 min',
        version: '0.1',
        lastUpdated: '2026-06-28',
        purposeKey: 'chapters.engineering-principles.purpose',
        keyQuestionKey: 'chapters.engineering-principles.key_question',
        dependencies: ['ai-architecture'],
        relatedChapters: ['ai-architecture', 'privacy'],
        researchConfidence: 'High',
      },
      {
        slug: 'privacy',
        chapterNumber: 37,
        volumeId: 5,
        status: 'Researching',
        readingTime: '8 min',
        version: '0.1',
        lastUpdated: '2026-06-28',
        purposeKey: 'chapters.privacy.purpose',
        keyQuestionKey: 'chapters.privacy.key_question',
        dependencies: ['engineering-principles'],
        relatedChapters: ['engineering-principles', 'security'],
        researchConfidence: 'High',
      },
      {
        slug: 'security',
        chapterNumber: 38,
        volumeId: 5,
        status: 'Researching',
        readingTime: '7 min',
        version: '0.1',
        lastUpdated: '2026-06-28',
        purposeKey: 'chapters.security.purpose',
        keyQuestionKey: 'chapters.security.key_question',
        dependencies: ['privacy'],
        relatedChapters: ['privacy', 'business-model'],
        researchConfidence: 'High',
      },
      {
        slug: 'business-model',
        chapterNumber: 39,
        volumeId: 5,
        status: 'Researching',
        readingTime: '6 min',
        version: '0.1',
        lastUpdated: '2026-06-28',
        purposeKey: 'chapters.business-model.purpose',
        keyQuestionKey: 'chapters.business-model.key_question',
        dependencies: [],
        relatedChapters: ['security', 'development-phases'],
        researchConfidence: 'High',
      },
      {
        slug: 'development-phases',
        chapterNumber: 40,
        volumeId: 5,
        status: 'Researching',
        readingTime: '7 min',
        version: '0.1',
        lastUpdated: '2026-06-28',
        purposeKey: 'chapters.development-phases.purpose',
        keyQuestionKey: 'chapters.development-phases.key_question',
        dependencies: ['business-model'],
        relatedChapters: ['business-model', 'research-methodology'],
        researchConfidence: 'High',
      },
      {
        slug: 'research-methodology',
        chapterNumber: 41,
        volumeId: 5,
        status: 'Researching',
        readingTime: '8 min',
        version: '0.1',
        lastUpdated: '2026-06-28',
        purposeKey: 'chapters.research-methodology.purpose',
        keyQuestionKey: 'chapters.research-methodology.key_question',
        dependencies: [],
        relatedChapters: ['development-phases', 'building-saule'],
        researchConfidence: 'Medium',
      },
      {
        slug: 'building-saule',
        chapterNumber: 42,
        volumeId: 5,
        status: 'Researching',
        readingTime: '8 min',
        version: '0.1',
        lastUpdated: '2026-06-28',
        purposeKey: 'chapters.building-saule.purpose',
        keyQuestionKey: 'chapters.building-saule.key_question',
        dependencies: ['research-methodology'],
        relatedChapters: ['research-methodology', 'engineering-principles'],
        researchConfidence: 'High',
      },
    ],
  },
];

// Enrich volumes with dynamic research appendices (stable slugs, dynamic computed numbers)
volumes.forEach((vol) => {
  if (!vol.appendices) {
    vol.appendices = [];
  }
  const staticCount = vol.appendices.length;
  vol.appendices.push(
    {
      slug: `volume-${vol.id}-open-questions`,
      appendixNumber: staticCount + 1,
      volumeId: vol.id,
      status: 'Drafting',
      readingTime: '5 min',
      version: '0.1',
      lastUpdated: '2026-06-28',
      purposeKey: '',
      keyQuestionKey: '',
      dependencies: [],
      relatedChapters: [],
      researchConfidence: 'High',
    },
    {
      slug: `volume-${vol.id}-design-decisions`,
      appendixNumber: staticCount + 2,
      volumeId: vol.id,
      status: 'Drafting',
      readingTime: '5 min',
      version: '0.1',
      lastUpdated: '2026-06-28',
      purposeKey: '',
      keyQuestionKey: '',
      dependencies: [],
      relatedChapters: [],
      researchConfidence: 'High',
    },
    {
      slug: `volume-${vol.id}-references`,
      appendixNumber: staticCount + 3,
      volumeId: vol.id,
      status: 'Drafting',
      readingTime: '5 min',
      version: '0.1',
      lastUpdated: '2026-06-28',
      purposeKey: '',
      keyQuestionKey: '',
      dependencies: [],
      relatedChapters: [],
      researchConfidence: 'High',
    }
  );
});

export function getAllChapters(): ChapterMetadata[] {
  return volumes.flatMap((v) => v.chapters);
}

export function getChapterBySlug(slug: string): ChapterMetadata | undefined {
  return getAllChapters().find((c) => c.slug === slug);
}

export function getVolumeByChapterSlug(slug: string): Volume | undefined {
  return volumes.find((v) => v.chapters.some((c) => c.slug === slug));
}

export function getAllAppendices(): AppendixMetadata[] {
  return volumes.flatMap((v) => v.appendices || []);
}

export function getAppendixBySlug(slug: string): AppendixMetadata | undefined {
  return getAllAppendices().find((a) => a.slug === slug);
}

export function getVolumeByAppendixSlug(slug: string): Volume | undefined {
  return volumes.find((v) => (v.appendices || []).some((a) => a.slug === slug));
}

const allChapters = getAllChapters();

export const bookConfig = {
  version: '0.1',
  currentStatusKey: 'dashboard.status_desc',
  volumeCount: volumes.length,
  chapterCount: allChapters.length,
  writtenChaptersCount: allChapters.filter((chapter) => chapter.status !== 'Researching').length,
  lastUpdated: allChapters.reduce(
    (latest, chapter) => (chapter.lastUpdated > latest ? chapter.lastUpdated : latest),
    '',
  ),
  // These are editorial research totals that are not represented one-to-one in chapter metadata.
  researchSourcesCount: 28,
  designDecisionsCount: 15,
  openQuestionsCount: 34,
};
